### ISSUE TITLE
Issues with the example code

### ISSUE THREAD

**Issue by bortzmeyer** [dantecatalfamo/zig-dns#2]
The example code in `README.md` does not compile:

- `Message.from_bytes` should be `dns.Message.from_bytes` 
- Allocators are missing in the calls to `from_bytes` and `to_bytes`

**Comment by dantecatalfamo** [comment]
Thanks! Fixed in https://github.com/dantecatalfamo/zig-dns/commit/6074d9714b2523533820e020d9b7c619b8aa0401
