### ISSUE TITLE
Variables are not changed

### ISSUE THREAD

**Issue by bortzmeyer** [dantecatalfamo/zig-dns#6]
The very last Zig now rejects `var` is the [value is never changed](https://ziggit.dev/t/error-local-variable-is-never-mutated/2238). This creates issues with zig-dns:

```
src/iterative.zig:71:9: error: local variable is never mutated
    var message_bytes = try message.to_bytes(allocator);
        ^~~~~~~~~~~~~
src/iterative.zig:71:9: note: consider using 'const'
src/main.zig:35:9: error: local variable is never mutated
    var message_bytes = try message.to_bytes(allocator);
        ^~~~~~~~~~~~~
src/main.zig:35:9: note: consider using 'const'
```

**Comment by dantecatalfamo** [comment]
Thanks for the issue. I have to tackle a couple of issues with the latest zig master. They also changed the reader/writer interfaces and some built-in enum values.
